apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tutum
  labels:
    k8s-app: tutum-logging
spec:
  selector:
    matchLabels:
      name: tutum
  template:
    metadata:
      labels:
        name: tutum
    spec:
      containers:
      - name: tutum
        image: tutum/hello-world
===================================================

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tutum-helloworld
  namespace: kube-system
  labels:
    k8s-app: tutum-logging
spec:
  selector:
    matchLabels:
      name: tutum-helloworld
  template:
    metadata:
      labels:
        name: tutum-helloworld
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: tutum
        image: tutum/hello-world
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers






