apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: mysql
spec:
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: app-config
      containers:
      - image: xcoulon/go-url-shortener:0.2.0
        name: go-url-shortener
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_HOST
          value: postgres
        - name: POSTGRES_PORT
          value: "5432"
        - name: CONFIG_FILE
          value: /etc/config/config.yaml
        - name: POSTGRES_DATABASE
          valueFrom:
            secretKeyRef:
              name: database-secret-config
              key: dbname
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: DB_PASSWORD
