apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7.8
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: mydb-secret
                key: db-name
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: mydb-secret
                key: db-user
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mydb-secret
                key: db-password
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mydb-secret
                key: db-rootpassword      
      
