apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-profile

data:
  profile: mysql
  application-mysql.properties: |
    database=mysql
    spring.datasource.url=jdbc:mysql://mysql-service/petclinic
    spring.datasource.username=petclinic
    spring.datasource.password=petclinic
    spring.datasource.initialization-mode=always
