# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

# Virtual Machine 1 Configurations
  config.vm.define "VM1" do |vm1|
    vm1.vm.hostname = "VM1"
    vm1.vm.box = "centos/7"
    vm1.vm.network "forwarded_port", guest: 80, host: 8080
    vm1.vm.network "private_network", ip: "172.28.128.4"

#   Provider Settings
    vm1.vm.provider "virtualbox" do |vb|
       vb.name = "VM1"
       vb.gui = false
       vb.memory = "1024"
    end

    Provision Settings
     vm1.vm.provision "shell", inline: <<-SHELL
      yum -y epel-release
      yum -y ansible vim
   SHELL

   vm1.vm.provision "shell", run: "always", inline: <<-SHELL
     echo "Centos VM1 is ready "
   SHELL
  end

# Virtual Machine 2  Configurations
  config.vm.define "VM2" do |vm2|
    vm2.vm.hostname = "VM2"
    vm2.vm.box = "centos/7"
    vm2.vm.network "private_network", ip:"172.28.128.5"
 #   vm2.vm.network "forwarded_port", guest: 80, host: 8081, host_ip: "127.0.0.1"

  vm2.vm.provider "virtualbox" do |vb|
     vb.name = "VM2"
     vb.gui = false
     vb.memory = "1024"
  end

   vm2.vm.provision "shell", run: "always", inline: <<-SHELL
     echo "Centos VM2 is ready"
   SHELL
  end

# Virtual Machine 3 Configurations
  config.vm.define "VM3" do |vm3|
    vm3.vm.hostname = "VM3"
    vm3.vm.box = "bento/ubuntu-16.04" 
    vm3.vm.network "private_network", ip: "172.28.128.6"
    vm3.vm.network "forwarded_port", guest: 3306, host: 3306

  vm3.vm.provider "virtualbox" do |vb|
     vb.name = "VM3"
     vb.gui = false
     vb.memory = "1024"
  end

   vm3.vm.provision "shell", run: "always", inline: <<-SHELL
     echo "Ubuntu VM3 is ready"
   SHELL
  end

end
